import 'package:flutter/material.dart';

const kMainColor = Color(0xffffc12f);
const kSecondryColor = Color(0xffffe6ac);
const kProductCollection = 'products';
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const kProductDecsription = 'productDecsription';
const kQuantity = 'Quantity';
const kUnActiveColor = Color(0xffc1bdb8);
const kJacket = 'jackets';
const kShoes = 'shoes';
const kTshirt = 't-shirt';
const kTrousers = 'trousers';
const kOrders = 'orders';
const kOrdersDetails = 'ordersDetails';
const kTotalPrice = 'totalPrice';
const kAdress = 'adress';
const kKeepMeLoggedIn = 'KeepMeLoggedIn';
